// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveFile() {
  return window['go']['main']['App']['SaveFile']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
